--36. Tính tổng số lượng của từng sản phẩm bán ra trong tháng 10/2006.
SELECT CTHD.MASP, COUNT(CTHD.MASP) AS TONGSO
FROM HOADON, CTHD
WHERE HOADON.SOHD = CTHD.SOHD AND MONTH(HOADON.NGHD) = '10' AND YEAR(HOADON.NGHD) = '2006'
GROUP BY MASP
--37. Tính doanh thu bán hàng của từng tháng trong năm 2006.
SELECT MONTH(HOADON.NGHD) AS THANG, SUM(HOADON.TRIGIA) AS DOANHTHU
FROM HOADON 
WHERE YEAR(HOADON.NGHD) = '2006'
GROUP BY MONTH(HOADON.NGHD)
--38. Tìm hóa đơn có mua ít nhất 4 sản phẩm khác nhau.
SELECT SOHD, COUNT(MASP) AS SOSP
FROM CTHD
GROUP BY SOHD
HAVING COUNT(MASP) >= 4
--39. Tìm hóa đơn có mua 3 sản phẩm do “Viet Nam” sản xuất (3 sản phẩm khác nhau).
SELECT A.SOHD, COUNT(A.MASP) AS SL
FROM 
(
SELECT *
FROM CTHD
WHERE CTHD.MASP IN
(
SELECT DISTINCT CTHD.MASP
FROM SANPHAM, CTHD
WHERE SANPHAM.MASP = CTHD.MASP AND SANPHAM.NUOCSX = 'Viet Nam'
)
) AS A
GROUP BY A.SOHD
HAVING COUNT(A.MASP) = '3'
--40. Tìm khách hàng (MAKH, HOTEN) có số lần mua hàng nhiều nhất.
SELECT TOP 1 HOADON.MAKH, COUNT(*) AS SOLANMUA
FROM HOADON
WHERE HOADON.MAKH IS NOT NULL
GROUP BY HOADON.MAKH
ORDER BY SOLANMUA DESC
--41. Tháng mấy trong năm 2006, doanh số bán hàng cao nhất ?
SELECT TOP 1 MONTH(HOADON.NGHD) AS THANG
FROM HOADON
WHERE YEAR(HOADON.NGHD) = '2006'
GROUP BY MONTH(HOADON.NGHD) 
ORDER BY SUM(HOADON.TRIGIA)  DESC
--42. Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2006.
SELECT MASP, TENSP
FROM SANPHAM
WHERE SANPHAM.MASP IN
(
SELECT TOP 1 CTHD.MASP
FROM CTHD, HOADON
WHERE HOADON.SOHD = CTHD.SOHD
GROUP BY CTHD.MASP
ORDER BY SUM(CTHD.SL) ASC
)
--43. *Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
SELECT B.NUOCSX, B.MASP, B.TENSP
FROM
(
SELECT SANPHAM.NUOCSX, SANPHAM.MASP, SANPHAM.TENSP , SANPHAM.GIA
FROM SANPHAM
) AS B, 
(
SELECT SANPHAM.NUOCSX , MAX(GIA) AS MAXGIA
FROM SANPHAM
GROUP BY SANPHAM.NUOCSX
) AS A
WHERE B.NUOCSX = A.NUOCSX AND A.MAXGIA = B.GIA
GROUP BY B.NUOCSX, B.MASP, B.TENSP
--44. Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau.
SELECT SANPHAM.NUOCSX
FROM SANPHAM
GROUP BY SANPHAM.NUOCSX
HAVING COUNT(DISTINCT SANPHAM.GIA) >= 3
--45. *Trong 10 khách hàng có doanh số cao nhất, tìm khách hàng có số lần mua hàng nhiều nhất.
SELECT TOP 1 A.MAKH, COUNT(*) AS SOLANMUA
FROM 
(SELECT TOP 10 MAKH, DOANHSO
FROM KHACHHANG
GROUP BY MAKH, DOANHSO
ORDER BY DOANHSO DESC) AS A LEFT JOIN HOADON ON A.MAKH = HOADON.MAKH
GROUP BY A.MAKH
ORDER BY SOLANMUA DESC